version: '3'

services:
  test_db:
    image: postgres
    container_name: bits-and-bites-postgres-test
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5435:5432"
